### ISSUE TITLE
[Question] Extension.Json

### ISSUE THREAD

**Issue by huideaki** [zjklee/Handlebars.Net#40]
I saw that u did work to add a nuget package for Extension.Json to handle json document and elements. But seems like you removed everything ? Where did it all go and do you have any plans to readd them ?

**Comment by zjklee** [comment]
Hi @huideaki . 
Right now I'm in progress of merging all the changes from my fork to the trunk and I've reset my master to trunk's version as part of the migration.
Work related to Json support is preserved and will be migrated as well.
Follow updated in the trunk.

**Comment by oformaniuk** [comment]
New package for Handlebars.Net is published: https://www.nuget.org/packages/Handlebars.Net.Extension.Json/
